### ISSUE TITLE
INPUT not working when attempting this on a SBC

### ISSUE THREAD

**Issue by okwatts** [chelsea6502/BeebEater#12]
Hi, I noted your posting on 6502.org and have been trying it out on another SBC which is similar in Hardware to BenEater's. I don't have the LCD or PS2 so have grounded the ports for my VIA. Essentially I have 32 K less the top page which is for I/O hence VIA is located at $7f60 and ACIA at $7f70. I have changed the HiMem to $7f00 and can start and enter programs. I was having problems with the TIME working inside programs whereas it worked from the prompt. It appears to work now but occasionally I have had to hit reset and it works. I can type in and run an ASCII Mandelbrot program but if I try and capture input using the INPUT statement the system locks up after hitting return and needs to be reset. I can recover programs using the OLD command. So my question is whether there is an issue with accepting user input using the INPUT statement on Ben Eater's hardware? Or is this an issue in porting to my SBC.

**Comment by chelsea6502** [comment]
Hi okwatts! Thanks for confirming you've at least got it to a bootable state.

I haven't been able to replicate the TIME problem, but I can confirm that INPUT locks up on the main branch program. I'll have an investigation on the weekend.

**Comment by okwatts** [comment]
Thanks yes I think the TIME thing is better with the latest update. The
input issue is frustrating. Looking forward to hearing from you after you
have a chance to look at it.

**Comment by chelsea6502** [comment]
Okay! I think I figured it out! The problem was that I was not restoring the A, X and Y registers after exiting from the 'OSWORD0V' routine.

I've just pushed a fix for it now in the main branch, plus a few other tidy-ups. Let me know if that does it for you.

**Comment by okwatts** [comment]
Hi I was working on checking your update when my computer on which I was working seems to have failed. I've tried a number of things but so far haven't been able to resurrect it. While I was testing it appears that at least in small programs the INPUT issue is fixed. I tried the TIME issue and it works the first time through and then doesn't advance the time unless I reset. I then tried to test the INPUT on a larger program and had issues. About the that time the computer just quit responding. It's possible the last few issues may have been due to an imminent impending failure but I can't tell until I can get this sorted. I have tried a number of chip replacements and even replaced the crystal and cap for the 1.8MHz ACIA clock but so far nothing shows even when I go back to my other EEPROM application. I will have to try a more rigorous approach with a logic analyzer to see what is failing. I'll let you know if and when I can continue.

**Comment by chelsea6502** [comment]
hmmm....I haven't been able to replicate the TIME issue. It's interesting that calling TIME seems to pause it. Are you using the WDC 65c02, by any chance?

One issue that might be impacting your program is how it pastes into Coolterm. I find that it often skips characters. I'm about to push an update that has larger delays when sending characters. Pasting is slower, but it's more reliable.

One more thing you could try: Tie the ACIA  Pins 16 (DCDB) and 17 (DSRB) to ground. I found those floating pins cause unwanted interrupts and locked input. 

Let me know if those suggestions work, or if you find any more info about it.

PS: OMG I had no idea about the OLD command! That's going to save be a ton of time re-typing things after a reset!

**Comment by chelsea6502** [comment]
Thanks for that, that's helpful!

I can confirm I get the same issue too. I've attached screenshots below.

I'll have an investigate tonight. I'm very sure it's something to do with the escape handling that's causing TIME to bug out.

Thanks for this. It's interesting!

<img width="301" alt="Screenshot 2023-12-04 at 1 20 39 pm" src="https://github.com/chelsea6502/BeebEater/assets/122856043/e1580676-61f9-41b3-a23d-20943df64b69">

<img width="348" alt="Screenshot 2023-12-04 at 1 19 25 pm" src="https://github.com/chelsea6502/BeebEater/assets/122856043/de9d270f-255d-4541-8cbe-e545b5a479a0">

**Comment by chelsea6502** [comment]
Hi again, starting investigation now. I'm trying to get a bit more clarity on that program you've got there. 

What's the goal of it? If you have '100 GOTO 10', Q1 would almost always be equal to Q.

If you change it to 100 GOTO 20, it seems to be more in line with what I imagine you're trying to do:
<img width="307" alt="image" src="https://github.com/chelsea6502/BeebEater/assets/122856043/410596c3-677c-41f3-9a64-8cc96f8edb49">

**Comment by chelsea6502** [comment]
Okay, I found the issue! I put an 'SEI' at the start of the OSWORD routine, which means that the timer never gets incremented while that is set.

I've pushed an update that changes the 'SEI' to a 'CLI'. Give that a try, and let me know if it works for you.

I'm unsure what the implications are for enabling interrupts here, so I'll keep an eye out for any issues that may arise.

**Comment by okwatts** [comment]
Hi the new version doesn't really fix the issue. The program is intended to time the for next loop. The extra was just to confirm that input still behaved. I now see the a time printed of 1e-2 (I'm running at 4Mhz and have corrected the Timer variable to still get a 100Hz clock tick). I do also to see an occasional odd character on printout to the screen( not sure of the ascii code but a vertical bar with a right segment in the middle this looks to be in place of the CR). Then also after reset and OLD when the correct time is being shown the ESC key works almost immediately but when the wrong time is shown it takes some time for the ESC to be recognized.

I'm not sure if this helps but in your first update to me dated Nov 25 the time functioned properly whether ESC was used or not. The next update fixed the input issue but then the time changed after hitting ESC.
Thanks for trying on this.

**Comment by chelsea6502** [comment]
hmmm...I also get 1E-2, but only on the first iteration. After that it works fine for me. I figured it made sense, as the first one is likely just 1/100.

If you're getting it for every iteration, it must be that it only increments once and never again. I'll check if "free run mode" for the timer is properly set.

I've also been battling garbled characters on my RS-232. I'm going to look into implementing CTS/RTS and see if that helps.

Also note that I'm only supporting a 1mhz clock frequency that Ben Eater used. Anything else may have wacky results.

I'll look into all of these. Thanks!

**Comment by okwatts** [comment]
Hi Yes that seems to have fixed the issue with TIME after an ESC. I will continue to test with other programs to see if I run across any other issues.
